@startuml SchoolHRM_UseCase

skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam usecaseBorderColor #185FA5
skinparam usecaseBackgroundColor #E6F1FB
skinparam usecaseFontColor #0C447C
skinparam actorBorderColor #444441
skinparam actorFontColor #2C2C2A
skinparam packageBorderColor #888780
skinparam packageFontColor #444441
skinparam ArrowThickness 1


skinparam usecaseArrowThickness 2

actor "Visitatore" as Visitatore
actor "Studente"   as Studente
actor "Docente"    as Docente

Studente --|> Visitatore
Docente  --|> Visitatore

package "SchoolHRM" {
  usecase "Visualizza progetti"    as UC03
  usecase "Autenticazione"         as UC_auth
  usecase "Gestione CRUD"          as UC04
  usecase "Visualizza feedback"    as UC07
  usecase "Svolgi progetto"        as UC05
  usecase "Valuta docente"         as UC06
}

Visitatore --> UC03

Studente   --> UC_auth
Studente   --> UC05
Studente   --> UC06

Docente    --> UC_auth
Docente    --> UC04
Docente    --> UC07

UC04 .> UC03 : <<include>>
UC06 .> UC05 : <<extend>>

@enduml
